apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged
  namespace: cesi6  # ⚠️ REMPLACEZ par votre namespace !
  labels:
    test: "validation-privileged"
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    securityContext:
      privileged: true  # ❌ VIOLATION