apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-writable-root
  namespace: cesi6  # ⚠️ REMPLACEZ par votre namespace !
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-writable-root
  template:
    metadata:
      labels:
        app: nginx-writable-root
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          runAsUser: 101
          # ❌ VIOLATION : pas de readOnlyRootFilesystem: true